version: "3"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  pagespeed_exporter:
    image: foomo/pagespeed_exporter:latest
    restart: unless-stopped
    ports:
      - "9271:9271"

  prometheus:
    restart: unless-stopped
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/config.yml:/etc/prometheus/prometheus.yml:ro"
      - "prometheus_data:/prometheus"

  grafana:
    restart: unless-stopped
    image: grafana/grafana:latest
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./grafana/provisioning/:/etc/grafana/provisioning/"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=s3cr3t
