{
 "title": "Pagespeed",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(pagespeed_lighthouse_category_score,host)"
    }
   },
   {
    "name": "path",
    "label": "path",
    "query": {
     "query": "label_values(pagespeed_lighthouse_category_score,path)"
    }
   },
   {
    "name": "strategy",
    "label": "strategy",
    "query": {
     "query": "label_values(pagespeed_lighthouse_category_score,strategy)"
    }
   },
   { "name": "diff", "label": "Diff", "query": "1d,2d,1w, 2w, 1m" }
  ]
 },
 "panels": [
  {
   "title": "Overview ($strategy)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "strategy",
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "#### Lighthouse scores for $strategy\n* 0 to 49 (slow): Red\n* 50 to 89 (average): Orange\n* 90 to 100 (fast): Green\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Performance Score",
   "type": "gauge",
   "description": "Performance Score",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pagespeed_lighthouse_category_score{host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"performance\"} * 100"
    }
   ]
  },
  {
   "title": "Accessibility Score",
   "type": "gauge",
   "description": "The Accessibility score is a weighted average of all the accessibility audits. See Scoring Details for a full list of how each audit is weighted. The heavier-weighted audits have a bigger impact on your score.\n\nEach accessibility audit is pass or fail. Unlike the Performance audits, a page doesn't get points for partially passing an accessibility audit. For example, if some elements have screenreader-friendly names, but others don't, that page gets a 0 for the screenreader-friendly-names audit.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pagespeed_lighthouse_category_score{host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"accessibility\"} * 100"
    }
   ]
  },
  {
   "title": "SEO Score",
   "type": "gauge",
   "description": "Search Engine Optimization Score",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pagespeed_lighthouse_category_score{host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"seo\"} * 100"
    }
   ]
  },
  {
   "title": "Best Practices Score",
   "type": "gauge",
   "description": "Lighthouse returns a Best Practices score between 0 and 100. 0 is the worst possible score, and 100 is the best.\n\nThe Best Practices audits are equally weighted. To calculate how much each audit contributes to your overall Best Practices score, count the number of Best Practices audits, then divide 100 by that number.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pagespeed_lighthouse_category_score{host=\"$host\",path=\"$path\",strategy=\"$strategy\",category=\"best-practices\"} * 100"
    }
   ]
  },
  {
   "title": "Timings / Scores / Audits ($strategy)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "strategy",
   "targets": [
    {}
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pagespeed_lighthouse_total_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "Total Time"
    },
    {
     "expr": "pagespeed_lighthouse_first_contentful_paint_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "First Contentful Paint"
    },
    {
     "expr": "pagespeed_lighthouse_first_cpu_idle_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "First CPU Idle"
    },
    {
     "expr": "pagespeed_lighthouse_first_meaningful_paint_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "First Meaningful Paint"
    },
    {
     "expr": "pagespeed_lighthouse_interactive_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "Interactive"
    },
    {
     "expr": "pagespeed_lighthouse_speed_index_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "Content Speed Index "
    },
    {
     "expr": "pagespeed_lighthouse_bootup_time_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "JS Bootup Time"
    },
    {
     "expr": "pagespeed_lighthouse_largest_contentful_paint_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "Largest Contentful Paint"
    },
    {
     "expr": "pagespeed_lighthouse_mainthread_work_breakdown_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "Mainthread Work"
    },
    {
     "expr": "pagespeed_lighthouse_cumulative_layout_shift_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "Cumulative Layout Shift"
    },
    {
     "expr": "pagespeed_lighthouse_total_blocking_time_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "Total Blacking Time"
    },
    {
     "expr": "pagespeed_lighthouse_server_response_time_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "Server Response Time"
    },
    {
     "expr": "pagespeed_lighthouse_max_potential_fid_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "Max Potential FID"
    },
    {
     "expr": "pagespeed_lighthouse_estimated_input_latency_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "Estimated Input Latency"
    }
   ]
  },
  {
   "title": "Timing Diff $diff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "delta(pagespeed_lighthouse_total_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "Total Time"
    },
    {
     "expr": "delta(pagespeed_lighthouse_first_contentful_paint_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "First Contentful Paint"
    },
    {
     "expr": "delta(pagespeed_lighthouse_first_cpu_idle_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "First CPU Idle"
    },
    {
     "expr": "delta(pagespeed_lighthouse_first_meaningful_paint_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "First Meaningful Paint"
    },
    {
     "expr": "delta(pagespeed_lighthouse_interactive_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "Interactive"
    },
    {
     "expr": "delta(pagespeed_lighthouse_speed_index_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "Content Speed Index "
    },
    {
     "expr": "delta(pagespeed_lighthouse_bootup_time_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "JS Bootup Time"
    },
    {
     "expr": "delta(pagespeed_lighthouse_largest_contentful_paint_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "Largest Contentful Paint"
    },
    {
     "expr": "delta(pagespeed_lighthouse_mainthread_work_breakdown_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "Mainthread Work"
    },
    {
     "expr": "delta(pagespeed_lighthouse_cumulative_layout_shift_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "Cumulative Layout Shift"
    },
    {
     "expr": "delta(pagespeed_lighthouse_total_blocking_time_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "Total Blacking Time"
    },
    {
     "expr": "delta(pagespeed_lighthouse_server_response_time_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "Server Response Time"
    },
    {
     "expr": "delta(pagespeed_lighthouse_max_potential_fid_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "Max Potential FID"
    },
    {
     "expr": "delta(pagespeed_lighthouse_estimated_input_latency_duration_seconds{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "Estimated Input Latency"
    }
   ]
  },
  {
   "title": "Audit Scores",
   "type": "timeseries",
   "description": "https://developers.google.com/web/tools/lighthouse/v3/scoring",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pagespeed_lighthouse_audit_score{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}",
     "legendFormat": "{{audit}}"
    }
   ]
  },
  {
   "title": "Audit Diff $diff",
   "type": "timeseries",
   "description": "https://developers.google.com/web/tools/lighthouse/v3/scoring",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(pagespeed_lighthouse_audit_score{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])",
     "legendFormat": "{{audit}}"
    }
   ]
  },
  {
   "title": "Score History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pagespeed_lighthouse_category_score{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}*100 ",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Score History Diff $diff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "delta(pagespeed_lighthouse_category_score{host=\"$host\",path=\"$path\",strategy=\"$strategy\"}[$diff])*100",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Pagespeed Exporter Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pagespeed Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pagespeed_scrape_duration_seconds",
     "legendFormat": "scrape duration"
    }
   ]
  }
 ]
}