apiVersion: v1
kind: Service
metadata:
  name: {{ include "pagespeed-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pagespeed-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if .Values.prometheus.scrape }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.targetPort | quote }}
    prometheus.io/path: {{ .Values.prometheus.path | quote }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "pagespeed-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}